# Generated by Django 3.2.4 on 2021-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210622_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='mini_img',
            field=models.ImageField(upload_to='about/'),
        ),
    ]
